apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: daemonset-creator
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["daemonsets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
