apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecuresshserver
spec:
  selector:
    matchLabels:
      run: insecuresshserver
  replicas: 1
  template:
    metadata:
      labels:
        run: insecuresshserver
    spec:
      containers:
      - name: insecuresshserver
        image: raesene/insecure_ssh_container
        ports:
        - containerPort: 3456
---

apiVersion: v1
kind: Service
metadata:
  name: insecuresshserver
  labels: 
    run: insecuresshserver
spec:
  type: NodePort
  selector:
    run: insecuresshserver
  ports:
  - port: 3456
    nodePort: 32001


