apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssrf
spec:
  selector:
    matchLabels:
      run: ssrf
  replicas: 1
  template:
    metadata:
      labels:
        run: ssrf
    spec:
      containers:
      - name: ssrf
        image: raesene/ssrftester
        ports:
        - containerPort: 4567
---

apiVersion: v1
kind: Service
metadata:
  name: ssrf
  labels: 
    run: ssrf
spec:
  type: NodePort
  selector:
    run: ssrf
  ports:
  - port: 4567
    nodePort: 32001


